{% set name = "publicsuffix" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/publicsuffix-{{ version }}.tar.gz
  sha256: 22ce1d65ab6af5e9b2122e2443facdb93fb5c4abf24138099cb10fe7989f43b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - publicsuffix
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/publicsuffix/
  summary: Get a public suffix for a domain name using the Public Suffix List.
  license: MIT AND MPL-2.0
  license_file: LICENSE
  dev_url: https://www.tablix.org/~avian/git/publicsuffix.git/

extra:
  recipe-maintainers:
    - BastianZim
